source 'https://github.com/Chj1995/DXSpecs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

#use_frameworks!

platform :ios, '10.0'

target 'DXGlobalConfigHttpManagerKit_Example' do
  pod 'DXGlobalConfigHttpManagerKit', :path => '../'

  target 'DXGlobalConfigHttpManagerKit_Tests' do
    inherit! :search_paths

    
  end
end
